### ISSUE TITLE
python ./src/api_service.py 报错 404 not found

### ISSUE THREAD

**Issue by Solenyalyl** [xming521/WeClone#4]
INFO:     Started server process [27457]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:38270 - "GET / HTTP/1.1" 404 Not Found
页面ip为0.0.0的时候页面都打不开
改为127.0.0.1的时候，页面可以打开，但是显示为not found
页面显示为：
![image](https://github.com/user-attachments/assets/a75f768e-f62c-4490-992f-6ac1191a0f04)
请问一下是什么原因？

**Comment by Ifjy** [comment]
请问你解决了吗
