### ISSUE TITLE
怎么将微调过得模型删去？

### ISSUE THREAD

**Issue by Ifjy** [xming521/WeClone#8]
。。练出来可能过拟合了，不知道怎么重新生成
Q2：不知道make dataset下面的三个csv_to_json的区别

**Comment by xming521** [comment]
生成的adapter默认都在model_output里，删了或者给这个文件夹换个文件名就行
在同一人回答多句的情况下，有三种处理方式：
| 文件 | 处理方式 |
| --- | --- |
| csv_to_json.py | 用逗号连接 |
| csv_to_json-单句回答.py | 只选选最长的回答作为最终数据 |
| csv_to_json-单句多轮.py | 放在了提示词的'history'中 |

**Comment by Ifjy** [comment]
感谢！
